name: flip_card
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_flip_builder: ^0.1.3
  cupertino_icons: ^1.0.2
  flutter_tindercard: ^0.2.0
  flutter_modular: any
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.4
  build_runner:
  flutter_modular_test: 
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

